### ISSUE TITLE
Narrowing conversion issue with marchIntersections.cpp:420:2

### ISSUE THREAD

**Issue by sushrut5** [MarcoAttene/MeshFix-V2.1#14]
Newer compilers flag this as a warning/error.

**Comment by musicinmybrain** [comment]
This also depends on the signedness of the `char` type, since the narrowing conversion only occurs when some values in the initializer-list are negative but the type is unsigned. On platforms with signed `char` by default, and with a GCC-compatible compiler, you can reproduce this by adding `-funsigned-char` to the compiler flags.

The simplest fix is to change the type of `mc_triTable` from `const char [256][20]` to `const signed char [256][20]`. PR incoming.
